import {
  ArrowLeftRight,
  AudioLines,
  Binary,
  Box,
  Braces,
  CalendarClock,
  CalendarSync,
  CaseSensitive,
  Code2,
  Coffee,
  Container,
  Database,
  Eraser,
  FileCode,
  FileImage,
  FileKey,
  FileLock,
  FileOutput,
  FilePen,
  FilePenLine,
  FileSearch,
  FileSpreadsheet,
  Files,
  FileText,
  FileType,
  FileVideo,
  Fingerprint,
  GitCompare,
  Globe,
  Hash,
  ImageIcon,
  Images,
  KeyRound,
  KeySquare,
  LayoutGrid,
  LetterText,
  Link,
  MailCheck,
  MapPin,
  Minimize2,
  NotebookPen,
  Package,
  Palette,
  PlugZap,
  QrCode,
  Quote,
  Radio,
  Regex,
  Search,
  ShieldCheck,
  Signature,
  WholeWord,
} from 'lucide-react'
import { lazy } from 'react'
import { runtimeConfig } from '@/config/runtime.config'
import { CATEGORIES, type Tool } from '@/types/tool.types'

export const tools: Tool[] = [
  {
    title: 'Base64',
    path: '/base64',
    description: 'Encode or decode text from and to the Base64 encoding format',
    icon: FileText,
    categories: [CATEGORIES.ENCODING],
    searchTags: ['base64', 'encoder', 'decoder', 'encoding', 'decoding', 'text'],
    component: lazy(() => import('@/tools/Base64')),
    online: false,
  },
  {
    title: 'URL Encoder/Decoder',
    path: '/url',
    description: 'Encode or decode text from and to the URL encoding format',
    icon: Link,
    categories: [CATEGORIES.ENCODING],
    searchTags: ['url', 'encoder', 'decoder', 'percent', 'encoding', 'uri'],
    component: lazy(() => import('@/tools/URL')),
    online: false,
  },
  {
    title: 'Diff Checker',
    path: '/diff-checker',
    description: 'Compare text to find the difference between two text files',
    icon: GitCompare,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['diff', 'text', 'checker', 'compare', 'difference'],
    component: lazy(() => import('@/tools/DiffChecker')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'Certificate Decoder',
    path: '/certificate-decoder',
    description: 'Decode PEM encoded X509 certificates',
    icon: FileKey,
    categories: [CATEGORIES.SECURITY],
    searchTags: ['certificate', 'ssl', 'tls', 'decoder', 'pem', 'x509', 'https'],
    component: lazy(() => import('@/tools/CertificateDecoder')),
    online: false,
    dependencies: [
      {
        name: '@peculiar/x509',
        url: 'https://www.npmjs.com/package/@peculiar/x509',
      },
    ],
  },
  {
    title: 'Protobuf Decoder',
    path: '/protobuf-decoder',
    description: 'Read raw protobuf buffers and inspect field values',
    icon: Package,
    categories: [CATEGORIES.ENCODING, CATEGORIES.DEVELOPMENT],
    searchTags: ['protobuf', 'decoder', 'protocol', 'buffers', 'binary', 'grpc'],
    component: lazy(() => import('@/tools/ProtobufDecoder')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/protobuf-decoder',
        url: 'https://www.npmjs.com/package/@goodtools/protobuf-decoder',
      },
    ],
  },
  {
    title: 'Java Object Deserializer',
    path: '/java-deserialize',
    description: 'Decode serialized Java objects and inspect their data',
    icon: Coffee,
    categories: [CATEGORIES.SECURITY, CATEGORIES.DEVELOPMENT],
    searchTags: ['java', 'deserializer', 'serialization', 'object', 'inspect'],
    component: lazy(() => import('@/tools/JavaDeserializer')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/jdserialize',
        url: 'https://www.npmjs.com/package/@goodtools/jdserialize',
      },
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'Docker Browser',
    path: '/docker-browser',
    description: 'Inspect a docker image and its file system',
    icon: Container,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['docker', 'image', 'browser', 'oci', 'container', 'filesystem', 'layers'],
    component: lazy(() => import('@/tools/ImageBrowser')),
    online: true,
    dependencies: [
      {
        name: 'containerd',
        url: 'https://github.com/containerd/containerd',
      },
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'WHOIS',
    path: '/whois',
    description: 'Search the whois database for verified registration information',
    icon: Search,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['whois', 'lookup', 'domain', 'registration', 'owner'],
    component: lazy(() => import('@/tools/Whois')),
    online: true,
    dependencies: [
      {
        name: 'likexian/whois',
        url: 'https://github.com/likexian/whois',
      },
    ],
  },
  {
    title: 'DNS Lookup',
    path: '/dns',
    description: 'Lookup most common DNS record types for a domain',
    icon: Globe,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['dns', 'lookup', 'domain', 'records', 'a', 'aaaa', 'mx', 'cname', 'txt'],
    component: lazy(() => import('@/tools/DNS')),
    online: true,
    dependencies: [
      {
        name: 'miekg/dns',
        url: 'https://github.com/miekg/dns',
      },
    ],
  },
  {
    title: 'Email Security Checker',
    path: '/email-security',
    description: 'Check a domain’s SPF, DKIM, DMARC, MX, MTA-STS, TLS-RPT and BIMI records',
    icon: MailCheck,
    categories: [CATEGORIES.NETWORK, CATEGORIES.SECURITY],
    searchTags: [
      'email',
      'spf',
      'dkim',
      'dmarc',
      'mx',
      'mta-sts',
      'tls-rpt',
      'bimi',
      'spoofing',
      'deliverability',
      'dns',
    ],
    component: lazy(() => import('@/tools/EmailSecurity')),
    online: true,
  },
  {
    title: 'JWT Decoder',
    path: '/jwt',
    description: 'Decode JSON Web Tokens, inspect their claims and verify signatures (HS, RS, PS, ES, EdDSA)',
    icon: KeyRound,
    categories: [CATEGORIES.SECURITY, CATEGORIES.ENCODING],
    searchTags: [
      'jwt',
      'json web token',
      'jws',
      'bearer',
      'token',
      'decode',
      'verify',
      'claims',
      'hs256',
      'rs256',
      'oauth',
      'oidc',
    ],
    component: lazy(() => import('@/tools/JwtDecoder')),
    online: false,
  },
  {
    title: 'File Identifier',
    path: '/file-identifier',
    description: 'Find out what a file really is, and flag files whose extension lies about their content',
    icon: FileSearch,
    categories: [CATEGORIES.SECURITY, CATEGORIES.DEVELOPMENT],
    searchTags: [
      'file type',
      'identify',
      'detect',
      'magika',
      'magic bytes',
      'signature',
      'mime',
      'extension',
      'mismatch',
      'malware',
      'file command',
    ],
    component: lazy(() => import('@/tools/FileIdentifier')),
    online: false,
    dependencies: [
      { name: 'Magika (Apache-2.0)', url: 'https://github.com/google/magika' },
      { name: 'onnxruntime-web', url: 'https://www.npmjs.com/package/onnxruntime-web' },
    ],
    notice:
      'This tool downloads a ~17 MB AI model and runtime once to identify files in your browser. Your files never leave your device.',
  },
  {
    title: 'Hash Calculator',
    path: '/hash',
    description: 'Calculate hashes for popular message digest algorithms',
    icon: Hash,
    categories: [CATEGORIES.SECURITY, CATEGORIES.ENCODING],
    searchTags: ['hash', 'calculator', 'digest', 'md5', 'sha256', 'sha384', 'sha512', 'checksum'],
    component: lazy(() => import('@/tools/HashCalculator')),
    online: false,
    dependencies: [
      {
        name: 'node-forge',
        url: 'https://www.npmjs.com/package/node-forge',
      },
    ],
  },
  {
    title: 'Binary Explorer',
    path: '/binary-explorer',
    description: 'Inspect ELF, PE and Mach-O executables: headers, sections, imports, exports, strings and hex',
    icon: Binary,
    categories: [CATEGORIES.SECURITY, CATEGORIES.DEVELOPMENT],
    searchTags: [
      'elf',
      'pe',
      'exe',
      'dll',
      'mach-o',
      'macho',
      'executable',
      'binary',
      'imports',
      'exports',
      'sections',
      'entropy',
      'strings',
      'hex',
      'reverse engineering',
      'malware',
    ],
    component: lazy(() => import('@/tools/BinaryExplorer')),
    online: false,
  },
  {
    title: 'Packet Dissector',
    path: '/packet-dissector',
    description: 'Wireshark packet dissection in your browser',
    icon: Radio,
    categories: [CATEGORIES.NETWORK, CATEGORIES.SECURITY],
    searchTags: ['wireshark', 'pcap', 'packet', 'dissector', 'network', 'capture', 'analysis'],
    component: lazy(() => import('@/tools/PacketDissector')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/wiregasm',
        url: 'https://www.npmjs.com/package/@goodtools/wiregasm',
      },
    ],
    notice: 'This tool downloads a large (~20 MB) WebAssembly build of Wireshark to dissect packets in your browser.',
  },
  {
    title: 'STL Repair',
    path: '/stl-repair',
    description: 'Repair and fix STL mesh files for 3D printing - fill holes, fix normals, remove duplicates',
    icon: Box,
    categories: [CATEGORIES['3D']],
    searchTags: ['stl', 'mesh', 'repair', '3d', 'print', 'fix', 'holes', 'normals', 'manifold', 'cad'],
    component: lazy(() => import('@/tools/STLRepair')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/meshrepair',
        url: 'https://www.npmjs.com/package/@goodtools/meshrepair',
      },
      {
        name: 'three.js',
        url: 'https://threejs.org',
      },
    ],
  },
  {
    title: 'HTTP & TLS Inspector',
    path: '/http-tls-inspector',
    description:
      'Follow redirects, grade security headers and inspect the TLS connection and certificate chain of a site',
    icon: ShieldCheck,
    categories: [CATEGORIES.NETWORK, CATEGORIES.SECURITY],
    searchTags: [
      'http',
      'https',
      'tls',
      'ssl',
      'certificate',
      'redirect',
      'headers',
      'security headers',
      'hsts',
      'csp',
      'cipher',
      'alpn',
    ],
    component: lazy(() => import('@/tools/HttpInspector')),
    online: true,
  },
  {
    title: "What's My IP",
    path: '/whats-my-ip',
    description: 'Find out your public IPv4 and IPv6 addresses',
    icon: MapPin,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['whats', 'my', 'ip', 'address', 'public', 'ipv4', 'ipv6'],
    component: lazy(() => import('@/tools/WhatsMyIP')),
    online: true,
  },
  {
    title: 'IP to Location',
    path: '/ip-location',
    description: 'Lookup details about IP addresses including their location, ASN and more',
    icon: MapPin,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['ip', 'address', 'location', 'geolocation', 'asn', 'city', 'country'],
    component: lazy(() => import('@/tools/IP2Location')),
    online: true,
    dependencies: [
      {
        name: 'oschwald/geoip2-golang',
        url: 'https://github.com/oschwald/geoip2-golang',
      },
      {
        name: 'GeoLite2-City',
        url: 'https://www.maxmind.com/en/geoip2-city',
      },
      {
        name: 'GeoLite2-ASN',
        url: 'https://www.maxmind.com',
      },
    ],
  },
  {
    title: 'MCP Browser',
    path: '/mcp',
    description: 'Connect to a Model Context Protocol server, browse its tools, resources and prompts, and call them',
    icon: PlugZap,
    categories: [CATEGORIES.DEVELOPMENT, CATEGORIES.NETWORK],
    searchTags: [
      'mcp',
      'model context protocol',
      'ai',
      'llm',
      'agent',
      'tools',
      'inspector',
      'json-rpc',
      'claude',
      'server',
    ],
    component: lazy(() => import('@/tools/McpBrowser')),
    // Talks directly to the server the user enters (no good.tools backend), but data does leave the browser
    online: true,
    dependencies: [
      { name: '@modelcontextprotocol/sdk', url: 'https://www.npmjs.com/package/@modelcontextprotocol/sdk' },
    ],
  },
  {
    title: 'JSON Formatter',
    path: '/json',
    description:
      'Beautify and format a JSON document, filter values using JSONPath queries and browse your object tree',
    icon: Braces,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['json', 'formatter', 'beautify', 'minify', 'jsonpath', 'validate'],
    component: lazy(() => import('@/tools/JsonFormatter')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
      {
        name: 'jsonpath',
        url: 'https://www.npmjs.com/package/jsonpath',
      },
    ],
  },
  {
    title: 'Markdown Notes',
    path: '/markdown-notes',
    description:
      'Write markdown notes with live preview, table of contents and mermaid diagrams, saved in your browser',
    icon: NotebookPen,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['markdown', 'md', 'notes', 'editor', 'preview', 'gfm', 'mermaid', 'diagram', 'codimd', 'hackmd'],
    component: lazy(() => import('@/tools/MarkdownNotes')),
    online: false,
    dependencies: [
      { name: '@monaco-editor/react', url: 'https://www.npmjs.com/package/@monaco-editor/react' },
      { name: 'marked', url: 'https://www.npmjs.com/package/marked' },
      { name: 'dompurify', url: 'https://www.npmjs.com/package/dompurify' },
      { name: 'mermaid', url: 'https://www.npmjs.com/package/mermaid' },
    ],
  },
  {
    title: 'Word Counter',
    path: '/word-counter',
    description: 'Count words, characters, sentences and paragraphs, with reading time and keyword density',
    icon: WholeWord,
    categories: [CATEGORIES.TEXT],
    searchTags: [
      'word count',
      'character count',
      'letter counter',
      'reading time',
      'speaking time',
      'keyword density',
      'text',
      'statistics',
    ],
    component: lazy(() => import('@/tools/WordCounter')),
    online: false,
  },
  {
    title: 'Case Converter',
    path: '/case-converter',
    description: 'Convert text to UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case and more',
    icon: CaseSensitive,
    categories: [CATEGORIES.TEXT],
    searchTags: [
      'uppercase to lowercase',
      'title case',
      'sentence case',
      'camelcase',
      'pascalcase',
      'snake case',
      'kebab case',
      'constant case',
      'text',
    ],
    component: lazy(() => import('@/tools/CaseConverter')),
    online: false,
  },
  {
    title: 'Lorem Ipsum Generator',
    path: '/lorem-ipsum',
    description: 'Generate lorem ipsum placeholder paragraphs, sentences or words as plain text, HTML or markdown',
    icon: LetterText,
    categories: [CATEGORIES.TEXT],
    searchTags: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text', 'generator', 'text'],
    component: lazy(() => import('@/tools/LoremIpsum')),
    online: false,
  },
  {
    title: 'JSON Escape',
    path: '/json-escape',
    description: 'Escape or unescape JSON special characters in text',
    icon: Quote,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['json', 'escape', 'unescape', 'quotes', 'string', 'format'],
    component: lazy(() => import('@/tools/JsonEscape')),
    online: false,
  },
  {
    title: 'XML Formatter',
    path: '/xml',
    description: 'Beautify and format an XML document, convert it to JSON or browse your object tree',
    icon: Code2,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['xml', 'formatter', 'beautify', 'minify', 'convert', 'json'],
    component: lazy(() => import('@/tools/XmlFormatter')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
      {
        name: 'fast-xml-parser',
        url: 'https://www.npmjs.com/package/fast-xml-parser',
      },
      {
        name: 'xml-formatter',
        url: 'https://www.npmjs.com/package/xml-formatter',
      },
    ],
  },
  {
    title: 'Code Beautifier / Minifier',
    path: '/code-formatter',
    description: 'Beautify or minify JavaScript, TypeScript, HTML, CSS and SCSS, and format SQL in many dialects',
    icon: FileCode,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: [
      'beautify',
      'minify',
      'js minifier',
      'css minifier',
      'html formatter',
      'sql formatter',
      'prettier',
      'javascript',
      'typescript',
      'scss',
    ],
    component: lazy(() => import('@/tools/CodeFormatter')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
      {
        name: 'prettier',
        url: 'https://www.npmjs.com/package/prettier',
      },
      {
        name: 'terser',
        url: 'https://www.npmjs.com/package/terser',
      },
      {
        name: 'csso',
        url: 'https://www.npmjs.com/package/csso',
      },
      {
        name: 'html-minifier-terser',
        url: 'https://www.npmjs.com/package/html-minifier-terser',
      },
      {
        name: 'sql-formatter',
        url: 'https://www.npmjs.com/package/sql-formatter',
      },
    ],
  },
  {
    title: 'Cron Expression',
    path: '/cron',
    description: 'Explain a cron expression in plain English and list its next run times in any time zone',
    icon: CalendarSync,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['cron', 'crontab', 'schedule', 'expression', 'explain', 'next run', 'quartz', 'timezone'],
    component: lazy(() => import('@/tools/CronExplainer')),
    online: false,
    dependencies: [
      { name: 'cronstrue', url: 'https://www.npmjs.com/package/cronstrue' },
      { name: 'croner', url: 'https://www.npmjs.com/package/croner' },
    ],
  },
  {
    title: 'UUID / ULID Generator',
    path: '/uuid',
    description: 'Generate UUID v4, v7, ULID and NanoID in bulk, or decode the version and timestamp of a UUID or ULID',
    icon: Fingerprint,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['uuid', 'guid', 'ulid', 'nanoid', 'v4', 'v7', 'generator', 'random', 'id', 'decode', 'timestamp'],
    component: lazy(() => import('@/tools/UuidGenerator')),
    online: false,
  },
  {
    title: 'Timestamp Converter',
    path: '/timestamp',
    description:
      'Convert Unix timestamps (s, ms, µs, ns) to ISO 8601, RFC 2822, local and relative time in any time zone',
    icon: CalendarClock,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['timestamp', 'unix', 'epoch', 'time', 'date', 'iso 8601', 'rfc 2822', 'timezone', 'utc', 'converter'],
    component: lazy(() => import('@/tools/TimestampConverter')),
    online: false,
  },
  {
    title: 'Regex Tester',
    path: '/regex',
    description: 'Test JavaScript regular expressions with live match highlighting, capture groups and replace',
    icon: Regex,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['regex', 'regexp', 'regular expression', 'match', 'test', 'replace', 'capture', 'groups'],
    component: lazy(() => import('@/tools/RegexTester')),
    online: false,
  },
  {
    title: 'Color Picker & Converter',
    path: '/color-picker',
    description:
      'Pick a color from the screen or convert any CSS color to HEX, RGB, HSL, HWB, OKLCH, OKLAB and CMYK, with a WCAG contrast checker',
    icon: Palette,
    categories: [CATEGORIES.DEVELOPMENT, CATEGORIES.IMAGE],
    searchTags: [
      'color picker',
      'colour',
      'hex to rgb',
      'rgb to hex',
      'hsl',
      'oklch',
      'oklab',
      'cmyk',
      'contrast checker',
      'wcag',
      'eyedropper',
      'tints',
      'shades',
    ],
    component: lazy(() => import('@/tools/ColorPicker')),
    online: false,
  },
  {
    title: 'Image Converter',
    path: '/image-converter',
    description:
      'Convert, resize and compress images to JPEG, PNG, WebP or AVIF with a before/after comparison, removing location metadata',
    icon: ImageIcon,
    categories: [CATEGORIES.IMAGE],
    searchTags: [
      'image',
      'convert',
      'jpeg',
      'jpg',
      'png',
      'webp',
      'avif',
      'heic',
      'resize',
      'compress',
      'compress image',
      'optimize',
      'optimise',
      'squoosh',
      'compare',
      'exif',
      'format',
      'photo',
    ],
    component: lazy(() => import('@/tools/ImageConverter')),
    online: false,
    dependencies: [
      {
        name: 'wasm-vips',
        url: 'https://www.npmjs.com/package/wasm-vips',
      },
    ],
  },
  {
    title: 'Video & Audio Converter',
    path: '/media-converter',
    description: 'Convert, compress and trim video and audio, extract the soundtrack or turn a clip into a GIF',
    icon: FileVideo,
    categories: [CATEGORIES.MEDIA],
    searchTags: [
      'video',
      'audio',
      'ffmpeg',
      'convert',
      'compress',
      'trim',
      'cut',
      'mp4',
      'webm',
      'mov',
      'mp3',
      'wav',
      'm4a',
      'aac',
      'gif',
      'extract audio',
    ],
    component: lazy(() => import('@/tools/MediaConverter')),
    online: false,
    dependencies: [
      { name: 'ffmpeg.wasm', url: 'https://github.com/ffmpegwasm/ffmpeg.wasm' },
      // Source of the exact pinned core release (0.12.10; the upstream v0.12.10 tag is the @ffmpeg/ffmpeg release)
      {
        name: '@ffmpeg/core-mt (GPL-2.0-or-later)',
        url: 'https://github.com/ffmpegwasm/ffmpeg.wasm/tree/71aa99d37c02a7b4c435275ca9ef50e612f6efa1/packages/core-mt',
      },
      { name: 'FFmpeg', url: 'https://ffmpeg.org' },
    ],
    notice:
      'This tool downloads a large (~10 MB) WebAssembly build of FFmpeg to convert files in your browser. Encoding runs on your device and is slower than desktop FFmpeg. The FFmpeg core is licensed under the GPL (2.0 or later); source: https://github.com/ffmpegwasm/ffmpeg.wasm/tree/71aa99d37c02a7b4c435275ca9ef50e612f6efa1/packages/core-mt',
  },
  {
    title: 'Remove Background',
    path: '/remove-background',
    description: 'Cut the background out of photos with an AI model that runs in your browser',
    icon: Eraser,
    categories: [CATEGORIES.IMAGE],
    searchTags: [
      'remove',
      'background',
      'cutout',
      'transparent',
      'png',
      'image',
      'photo',
      'ai',
      'segmentation',
      'mask',
    ],
    component: lazy(() => import('@/tools/RemoveBackground')),
    online: false,
    dependencies: [
      { name: 'onnxruntime-web', url: 'https://www.npmjs.com/package/onnxruntime-web' },
      { name: 'U²-Netp (Apache-2.0)', url: 'https://github.com/xuebinqin/U-2-Net' },
    ],
    notice:
      'This tool downloads a ~20 MB AI model and runtime once to remove backgrounds in your browser. Your images never leave your device.',
  },
  {
    title: 'Images to PDF',
    path: '/images-to-pdf',
    description:
      'Put images on PDF pages: page size, orientation, several per page, real ID-card size, or drag them anywhere',
    icon: FileImage,
    categories: [CATEGORIES.PDF, CATEGORIES.IMAGE],
    searchTags: ['image', 'jpg', 'jpeg', 'png', 'pdf', 'convert', 'scan', 'id card', 'cnic', 'photo', 'combine'],
    component: lazy(() => import('@/tools/ImagesToPdf')),
    online: false,
    dependencies: [{ name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' }],
  },
  {
    title: 'Merge PDF',
    path: '/merge-pdf',
    description: 'Combine several PDFs into one, in the order you choose',
    icon: Files,
    categories: [CATEGORIES.PDF],
    searchTags: ['pdf', 'merge', 'combine', 'join', 'append', 'order'],
    component: lazy(() => import('@/tools/MergePdf')),
    online: false,
    dependencies: [{ name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' }],
  },
  {
    title: 'Organize PDF',
    path: '/organize-pdf',
    description: 'Rotate, delete and reorder the pages of a PDF, extract a page range or split it into single pages',
    icon: LayoutGrid,
    categories: [CATEGORIES.PDF],
    searchTags: [
      'pdf',
      'organize',
      'rotate',
      'delete',
      'remove',
      'reorder',
      'sort',
      'pages',
      'split',
      'extract',
      'range',
    ],
    component: lazy(() => import('@/tools/OrganizePdf')),
    online: false,
    dependencies: [
      { name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' },
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
    ],
  },
  {
    title: 'PDF to Images',
    path: '/pdf-to-images',
    description: 'Turn every page of a PDF into a JPG, PNG or WebP image at the resolution you choose',
    icon: Images,
    categories: [CATEGORIES.PDF, CATEGORIES.IMAGE],
    searchTags: [
      'pdf',
      'pdf to jpg',
      'pdf to png',
      'pdf to webp',
      'pdf to image',
      'jpg',
      'jpeg',
      'png',
      'webp',
      'convert',
      'export',
      'pages',
      'dpi',
      'zip',
    ],
    component: lazy(() => import('@/tools/PdfToImages')),
    online: false,
    dependencies: [
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
      { name: 'fflate', url: 'https://www.npmjs.com/package/fflate' },
    ],
  },
  {
    title: 'Sign PDF',
    path: '/sign-pdf',
    description: 'Draw, type or upload a signature and place it anywhere on a PDF, with an optional date',
    icon: Signature,
    categories: [CATEGORIES.PDF],
    searchTags: ['sign pdf', 'esign', 'signature', 'sign', 'pdf', 'e-signature', 'initials', 'date', 'fill'],
    component: lazy(() => import('@/tools/SignPdf')),
    online: false,
    dependencies: [
      { name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' },
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
    ],
  },
  {
    title: 'Edit PDF',
    path: '/edit-pdf',
    description: 'Add text, images, white-out and highlights to a PDF, plus a watermark and page numbers',
    icon: FilePenLine,
    categories: [CATEGORIES.PDF],
    searchTags: [
      'edit pdf',
      'watermark pdf',
      'add page numbers',
      'annotate pdf',
      'add text to pdf',
      'pdf',
      'white-out',
      'highlight',
      'stamp',
    ],
    component: lazy(() => import('@/tools/EditPdf')),
    online: false,
    dependencies: [
      { name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' },
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
    ],
  },
  {
    title: 'PDF to Text',
    path: '/pdf-to-text',
    description: 'Extract the text of a PDF, page by page, with OCR for scanned pages',
    icon: FileType,
    categories: [CATEGORIES.PDF],
    searchTags: ['pdf', 'text', 'extract', 'txt', 'copy', 'convert', 'ocr', 'scan', 'tesseract'],
    component: lazy(() => import('@/tools/PdfToText')),
    online: false,
    dependencies: [
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
      { name: 'tesseract.js', url: 'https://github.com/naptha/tesseract.js' },
    ],
  },
  {
    title: 'PDF to Word',
    path: '/pdf-to-word',
    description: 'Convert a PDF to an editable Word document with headings, lists and images, and OCR for scans',
    icon: FilePen,
    categories: [CATEGORIES.PDF],
    searchTags: [
      'pdf to word',
      'pdf to docx',
      'convert pdf to word',
      'pdf',
      'word',
      'docx',
      'doc',
      'convert',
      'editable',
      'ocr',
      'scan',
    ],
    component: lazy(() => import('@/tools/PdfToWord')),
    online: false,
    dependencies: [
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
      { name: 'docx', url: 'https://www.npmjs.com/package/docx' },
      { name: 'tesseract.js', url: 'https://github.com/naptha/tesseract.js' },
    ],
  },
  {
    title: 'Protect / Unlock PDF',
    path: '/pdf-password',
    description: 'Add a password to a PDF (AES-256) or remove its password and restrictions',
    icon: FileLock,
    categories: [CATEGORIES.PDF, CATEGORIES.SECURITY],
    searchTags: ['pdf', 'password', 'protect', 'encrypt', 'unlock', 'decrypt', 'remove', 'restrictions', 'aes'],
    component: lazy(() => import('@/tools/PdfPassword')),
    online: false,
    dependencies: [{ name: 'qpdf', url: 'https://qpdf.sourceforge.io' }],
  },
  {
    title: 'SQL Query',
    path: '/sql-query',
    description: 'Query CSV, JSON, Parquet and SQLite files with SQL, right in your browser',
    icon: Database,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: [
      'sql',
      'query',
      'duckdb',
      'csv',
      'tsv',
      'json',
      'ndjson',
      'parquet',
      'sqlite',
      'db',
      'database',
      'table',
      'data',
    ],
    component: lazy(() => import('@/tools/SqlQuery')),
    online: false,
    dependencies: [
      { name: 'DuckDB-Wasm', url: 'https://github.com/duckdb/duckdb-wasm' },
      { name: 'sql.js', url: 'https://github.com/sql-js/sql.js' },
      { name: 'Apache Arrow', url: 'https://github.com/apache/arrow-js' },
    ],
    notice:
      'This tool downloads DuckDB (~8 MB of compressed WebAssembly) to run SQL on your files in your browser, plus sql.js (~650 KB) when you open a SQLite database.',
  },
  {
    title: 'Speech to Text',
    path: '/speech-to-text',
    description: 'Transcribe audio or video files and microphone recordings with Whisper, with SRT and VTT subtitles',
    icon: AudioLines,
    categories: [CATEGORIES.MEDIA],
    searchTags: [
      'speech',
      'text',
      'transcribe',
      'transcription',
      'whisper',
      'audio',
      'video',
      'subtitles',
      'captions',
      'srt',
      'vtt',
      'dictation',
      'voice',
    ],
    component: lazy(() => import('@/tools/SpeechToText')),
    online: false,
    dependencies: [
      { name: 'Transformers.js', url: 'https://github.com/huggingface/transformers.js' },
      { name: 'ONNX Runtime Web', url: 'https://onnxruntime.ai' },
      { name: 'Whisper (onnx-community)', url: 'https://huggingface.co/onnx-community/whisper-base' },
    ],
    notice:
      'This tool downloads a speech recognition model the first time and keeps it in your browser: about 50 MB for the default Whisper tiny, served by good.tools (or by Hugging Face if this site does not host it). The larger base (75–200 MB) and small (240–560 MB) models download from Hugging Face. Your audio never leaves your device.',
  },
  {
    title: 'Word to PDF',
    path: '/word-to-pdf',
    description: 'Convert a Word document (.docx) to PDF in your browser, with a page-by-page preview',
    icon: FileOutput,
    categories: [CATEGORIES.PDF],
    searchTags: [
      'word to pdf',
      'docx to pdf',
      'convert word to pdf',
      'word',
      'docx',
      'pdf',
      'convert',
      'print',
      'document',
    ],
    component: lazy(() => import('@/tools/WordToPdf')),
    online: false,
    dependencies: [{ name: 'docx-preview', url: 'https://github.com/VolodymyrBaydalka/docxjs' }],
  },
  {
    title: 'Compress PDF',
    path: '/compress-pdf',
    description: 'Make a PDF smaller by downscaling and recompressing its images and optimising its structure',
    icon: Minimize2,
    categories: [CATEGORIES.PDF],
    searchTags: ['pdf', 'compress', 'reduce', 'shrink', 'smaller', 'size', 'optimize', 'images', 'jpeg'],
    component: lazy(() => import('@/tools/CompressPdf')),
    online: false,
    dependencies: [
      { name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' },
      { name: 'wasm-vips', url: 'https://www.npmjs.com/package/wasm-vips' },
      { name: 'qpdf', url: 'https://qpdf.sourceforge.io' },
    ],
  },
  {
    title: 'Password Generator',
    path: '/password-generator',
    description: 'Generate strong random passwords or diceware-style passphrases, with an entropy estimate',
    icon: KeySquare,
    categories: [CATEGORIES.SECURITY],
    searchTags: ['password', 'passphrase', 'generator', 'random', 'diceware', 'eff', 'wordlist', 'entropy', 'secure'],
    component: lazy(() => import('@/tools/PasswordGenerator')),
    online: false,
    dependencies: [{ name: 'EFF short wordlist (CC BY 3.0 US)', url: 'https://www.eff.org/dice' }],
  },
  {
    title: 'CSV / Excel ↔ JSON',
    path: '/csv-json',
    description:
      'Convert CSV, TSV and Excel sheets to JSON and back, with delimiter detection, type inference, a preview table and .xlsx export',
    icon: FileSpreadsheet,
    categories: [CATEGORIES.DEVELOPMENT, CATEGORIES.ENCODING],
    searchTags: [
      'csv to json',
      'json to csv',
      'excel to json',
      'xlsx to csv',
      'csv',
      'tsv',
      'json',
      'excel',
      'xlsx',
      'spreadsheet',
      'sheet',
      'convert',
      'converter',
      'table',
    ],
    component: lazy(() => import('@/tools/CsvJson')),
    online: false,
    dependencies: [
      { name: 'papaparse', url: 'https://www.npmjs.com/package/papaparse' },
      { name: 'read-excel-file', url: 'https://www.npmjs.com/package/read-excel-file' },
      { name: 'write-excel-file', url: 'https://www.npmjs.com/package/write-excel-file' },
    ],
  },
  {
    title: 'YAML / JSON / TOML Converter',
    path: '/data-converter',
    description: 'Convert between YAML, JSON, TOML and CSV as you type, with errors pointing at the line and column',
    icon: ArrowLeftRight,
    categories: [CATEGORIES.DEVELOPMENT, CATEGORIES.ENCODING],
    searchTags: ['yaml', 'yml', 'json', 'toml', 'csv', 'convert', 'converter', 'config', 'transform'],
    component: lazy(() => import('@/tools/DataConverter')),
    online: false,
    dependencies: [
      { name: 'yaml', url: 'https://www.npmjs.com/package/yaml' },
      { name: 'smol-toml', url: 'https://www.npmjs.com/package/smol-toml' },
      { name: 'papaparse', url: 'https://www.npmjs.com/package/papaparse' },
    ],
  },
  {
    title: 'QR Code & Barcode',
    path: '/qr-code',
    description:
      'Generate QR codes and barcodes (EAN, UPC, Code 128, DataMatrix, PDF417, …), or read one from an image or your camera',
    icon: QrCode,
    categories: [CATEGORIES.ENCODING, CATEGORIES.IMAGE],
    searchTags: [
      'qr',
      'qrcode',
      'barcode',
      'ean',
      'upc',
      'code128',
      'code39',
      'datamatrix',
      'pdf417',
      'aztec',
      'itf',
      'generator',
      'reader',
      'scanner',
      'wifi',
      'camera',
      'url',
      'png',
      'svg',
    ],
    component: lazy(() => import('@/tools/QrCode')),
    online: false,
    dependencies: [
      { name: 'qrcode', url: 'https://www.npmjs.com/package/qrcode' },
      { name: 'bwip-js', url: 'https://www.npmjs.com/package/bwip-js' },
      { name: 'zxing-wasm', url: 'https://www.npmjs.com/package/zxing-wasm' },
      { name: 'zxing-cpp', url: 'https://github.com/zxing-cpp/zxing-cpp' },
    ],
  },
]

/** Tools shown in this deployment (online tools are hidden when DISABLE_ONLINE_TOOLS is set) */
export const availableTools = runtimeConfig.DISABLE_ONLINE_TOOLS ? tools.filter((t) => !t.online) : tools
