import {
  Box,
  Braces,
  Code2,
  Coffee,
  Container,
  FileImage,
  FileKey,
  FileLock,
  Files,
  FileText,
  FileType,
  GitCompare,
  Globe,
  Hash,
  ImageIcon,
  KeyRound,
  Link,
  MapPin,
  NotebookPen,
  Package,
  PlugZap,
  Quote,
  Radio,
  Search,
} from 'lucide-react'
import { lazy } from 'react'
import { runtimeConfig } from '@/config/runtime.config'
import { CATEGORIES, type Tool } from '@/types/tool.types'

export const tools: Tool[] = [
  {
    title: 'Base64',
    path: '/base64',
    description: 'Encode or decode text from and to the Base64 encoding format',
    icon: FileText,
    categories: [CATEGORIES.ENCODING],
    searchTags: ['base64', 'encoder', 'decoder', 'encoding', 'decoding', 'text'],
    component: lazy(() => import('@/tools/Base64')),
    online: false,
  },
  {
    title: 'URL Encoder/Decoder',
    path: '/url',
    description: 'Encode or decode text from and to the URL encoding format',
    icon: Link,
    categories: [CATEGORIES.ENCODING],
    searchTags: ['url', 'encoder', 'decoder', 'percent', 'encoding', 'uri'],
    component: lazy(() => import('@/tools/URL')),
    online: false,
  },
  {
    title: 'Diff Checker',
    path: '/diff-checker',
    description: 'Compare text to find the difference between two text files',
    icon: GitCompare,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['diff', 'text', 'checker', 'compare', 'difference'],
    component: lazy(() => import('@/tools/DiffChecker')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'Certificate Decoder',
    path: '/certificate-decoder',
    description: 'Decode PEM encoded X509 certificates',
    icon: FileKey,
    categories: [CATEGORIES.SECURITY],
    searchTags: ['certificate', 'ssl', 'tls', 'decoder', 'pem', 'x509', 'https'],
    component: lazy(() => import('@/tools/CertificateDecoder')),
    online: false,
    dependencies: [
      {
        name: '@peculiar/x509',
        url: 'https://www.npmjs.com/package/@peculiar/x509',
      },
    ],
  },
  {
    title: 'Protobuf Decoder',
    path: '/protobuf-decoder',
    description: 'Read raw protobuf buffers and inspect field values',
    icon: Package,
    categories: [CATEGORIES.ENCODING, CATEGORIES.DEVELOPMENT],
    searchTags: ['protobuf', 'decoder', 'protocol', 'buffers', 'binary', 'grpc'],
    component: lazy(() => import('@/tools/ProtobufDecoder')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/protobuf-decoder',
        url: 'https://www.npmjs.com/package/@goodtools/protobuf-decoder',
      },
    ],
  },
  {
    title: 'Java Object Deserializer',
    path: '/java-deserialize',
    description: 'Decode serialized Java objects and inspect their data',
    icon: Coffee,
    categories: [CATEGORIES.SECURITY, CATEGORIES.DEVELOPMENT],
    searchTags: ['java', 'deserializer', 'serialization', 'object', 'inspect'],
    component: lazy(() => import('@/tools/JavaDeserializer')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/jdserialize',
        url: 'https://www.npmjs.com/package/@goodtools/jdserialize',
      },
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'Docker Browser',
    path: '/docker-browser',
    description: 'Inspect a docker image and its file system',
    icon: Container,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['docker', 'image', 'browser', 'oci', 'container', 'filesystem', 'layers'],
    component: lazy(() => import('@/tools/ImageBrowser')),
    online: true,
    dependencies: [
      {
        name: 'containerd',
        url: 'https://github.com/containerd/containerd',
      },
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
    ],
  },
  {
    title: 'WHOIS',
    path: '/whois',
    description: 'Search the whois database for verified registration information',
    icon: Search,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['whois', 'lookup', 'domain', 'registration', 'owner'],
    component: lazy(() => import('@/tools/Whois')),
    online: true,
    dependencies: [
      {
        name: 'likexian/whois',
        url: 'https://github.com/likexian/whois',
      },
    ],
  },
  {
    title: 'DNS Lookup',
    path: '/dns',
    description: 'Lookup most common DNS record types for a domain',
    icon: Globe,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['dns', 'lookup', 'domain', 'records', 'a', 'aaaa', 'mx', 'cname', 'txt'],
    component: lazy(() => import('@/tools/DNS')),
    online: true,
    dependencies: [
      {
        name: 'miekg/dns',
        url: 'https://github.com/miekg/dns',
      },
    ],
  },
  {
    title: 'JWT Decoder',
    path: '/jwt',
    description: 'Decode JSON Web Tokens, inspect their claims and verify signatures (HS, RS, PS, ES, EdDSA)',
    icon: KeyRound,
    categories: [CATEGORIES.SECURITY, CATEGORIES.ENCODING],
    searchTags: [
      'jwt',
      'json web token',
      'jws',
      'bearer',
      'token',
      'decode',
      'verify',
      'claims',
      'hs256',
      'rs256',
      'oauth',
      'oidc',
    ],
    component: lazy(() => import('@/tools/JwtDecoder')),
    online: false,
  },
  {
    title: 'Hash Calculator',
    path: '/hash',
    description: 'Calculate hashes for popular message digest algorithms',
    icon: Hash,
    categories: [CATEGORIES.SECURITY, CATEGORIES.ENCODING],
    searchTags: ['hash', 'calculator', 'digest', 'md5', 'sha256', 'sha384', 'sha512', 'checksum'],
    component: lazy(() => import('@/tools/HashCalculator')),
    online: false,
    dependencies: [
      {
        name: 'node-forge',
        url: 'https://www.npmjs.com/package/node-forge',
      },
    ],
  },
  {
    title: 'Packet Dissector',
    path: '/packet-dissector',
    description: 'Wireshark packet dissection in your browser',
    icon: Radio,
    categories: [CATEGORIES.NETWORK, CATEGORIES.SECURITY],
    searchTags: ['wireshark', 'pcap', 'packet', 'dissector', 'network', 'capture', 'analysis'],
    component: lazy(() => import('@/tools/PacketDissector')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/wiregasm',
        url: 'https://www.npmjs.com/package/@goodtools/wiregasm',
      },
    ],
    notice: 'This tool downloads a large (~20 MB) WebAssembly build of Wireshark to dissect packets in your browser.',
  },
  {
    title: 'STL Repair',
    path: '/stl-repair',
    description: 'Repair and fix STL mesh files for 3D printing - fill holes, fix normals, remove duplicates',
    icon: Box,
    categories: [CATEGORIES['3D']],
    searchTags: ['stl', 'mesh', 'repair', '3d', 'print', 'fix', 'holes', 'normals', 'manifold', 'cad'],
    component: lazy(() => import('@/tools/STLRepair')),
    online: false,
    dependencies: [
      {
        name: '@goodtools/meshrepair',
        url: 'https://www.npmjs.com/package/@goodtools/meshrepair',
      },
      {
        name: 'three.js',
        url: 'https://threejs.org',
      },
    ],
  },
  {
    title: "What's My IP",
    path: '/whats-my-ip',
    description: 'Find out your public IPv4 and IPv6 addresses',
    icon: MapPin,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['whats', 'my', 'ip', 'address', 'public', 'ipv4', 'ipv6'],
    component: lazy(() => import('@/tools/WhatsMyIP')),
    online: true,
  },
  {
    title: 'IP to Location',
    path: '/ip-location',
    description: 'Lookup details about IP addresses including their location, ASN and more',
    icon: MapPin,
    categories: [CATEGORIES.NETWORK],
    searchTags: ['ip', 'address', 'location', 'geolocation', 'asn', 'city', 'country'],
    component: lazy(() => import('@/tools/IP2Location')),
    online: true,
    dependencies: [
      {
        name: 'oschwald/geoip2-golang',
        url: 'https://github.com/oschwald/geoip2-golang',
      },
      {
        name: 'GeoLite2-City',
        url: 'https://www.maxmind.com/en/geoip2-city',
      },
      {
        name: 'GeoLite2-ASN',
        url: 'https://www.maxmind.com',
      },
    ],
  },
  {
    title: 'MCP Browser',
    path: '/mcp',
    description: 'Connect to a Model Context Protocol server, browse its tools, resources and prompts, and call them',
    icon: PlugZap,
    categories: [CATEGORIES.DEVELOPMENT, CATEGORIES.NETWORK],
    searchTags: [
      'mcp',
      'model context protocol',
      'ai',
      'llm',
      'agent',
      'tools',
      'inspector',
      'json-rpc',
      'claude',
      'server',
    ],
    component: lazy(() => import('@/tools/McpBrowser')),
    // Talks directly to the server the user enters (no good.tools backend), but data does leave the browser
    online: true,
    dependencies: [
      { name: '@modelcontextprotocol/sdk', url: 'https://www.npmjs.com/package/@modelcontextprotocol/sdk' },
    ],
  },
  {
    title: 'JSON Formatter',
    path: '/json',
    description:
      'Beautify and format a JSON document, filter values using JSONPath queries and browse your object tree',
    icon: Braces,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['json', 'formatter', 'beautify', 'minify', 'jsonpath', 'validate'],
    component: lazy(() => import('@/tools/JsonFormatter')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
      {
        name: 'jsonpath',
        url: 'https://www.npmjs.com/package/jsonpath',
      },
    ],
  },
  {
    title: 'Markdown Notes',
    path: '/markdown-notes',
    description:
      'Write markdown notes with live preview, table of contents and mermaid diagrams, saved in your browser',
    icon: NotebookPen,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['markdown', 'md', 'notes', 'editor', 'preview', 'gfm', 'mermaid', 'diagram', 'codimd', 'hackmd'],
    component: lazy(() => import('@/tools/MarkdownNotes')),
    online: false,
    dependencies: [
      { name: '@monaco-editor/react', url: 'https://www.npmjs.com/package/@monaco-editor/react' },
      { name: 'marked', url: 'https://www.npmjs.com/package/marked' },
      { name: 'dompurify', url: 'https://www.npmjs.com/package/dompurify' },
      { name: 'mermaid', url: 'https://www.npmjs.com/package/mermaid' },
    ],
  },
  {
    title: 'JSON Escape',
    path: '/json-escape',
    description: 'Escape or unescape JSON special characters in text',
    icon: Quote,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['json', 'escape', 'unescape', 'quotes', 'string', 'format'],
    component: lazy(() => import('@/tools/JsonEscape')),
    online: false,
  },
  {
    title: 'XML Formatter',
    path: '/xml',
    description: 'Beautify and format an XML document, convert it to JSON or browse your object tree',
    icon: Code2,
    categories: [CATEGORIES.DEVELOPMENT],
    searchTags: ['xml', 'formatter', 'beautify', 'minify', 'convert', 'json'],
    component: lazy(() => import('@/tools/XmlFormatter')),
    online: false,
    dependencies: [
      {
        name: '@monaco-editor/react',
        url: 'https://www.npmjs.com/package/@monaco-editor/react',
      },
      {
        name: 'fast-xml-parser',
        url: 'https://www.npmjs.com/package/fast-xml-parser',
      },
      {
        name: 'xml-formatter',
        url: 'https://www.npmjs.com/package/xml-formatter',
      },
    ],
  },
  {
    title: 'Image Converter',
    path: '/image-converter',
    description: 'Convert images between formats: JPEG, PNG, WebP, AVIF with quality control',
    icon: ImageIcon,
    categories: [CATEGORIES.IMAGE],
    searchTags: ['image', 'convert', 'jpeg', 'png', 'webp', 'avif', 'format', 'photo'],
    component: lazy(() => import('@/tools/ImageConverter')),
    online: false,
    dependencies: [
      {
        name: 'wasm-vips',
        url: 'https://www.npmjs.com/package/wasm-vips',
      },
    ],
  },
  {
    title: 'Images to PDF',
    path: '/images-to-pdf',
    description:
      'Put images on PDF pages: page size, orientation, several per page, real ID-card size, or drag them anywhere',
    icon: FileImage,
    categories: [CATEGORIES.PDF, CATEGORIES.IMAGE],
    searchTags: ['image', 'jpg', 'jpeg', 'png', 'pdf', 'convert', 'scan', 'id card', 'cnic', 'photo', 'combine'],
    component: lazy(() => import('@/tools/ImagesToPdf')),
    online: false,
    dependencies: [{ name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' }],
  },
  {
    title: 'Merge PDF',
    path: '/merge-pdf',
    description: 'Combine several PDFs into one, in the order you choose',
    icon: Files,
    categories: [CATEGORIES.PDF],
    searchTags: ['pdf', 'merge', 'combine', 'join', 'append', 'order'],
    component: lazy(() => import('@/tools/MergePdf')),
    online: false,
    dependencies: [{ name: '@cantoo/pdf-lib', url: 'https://www.npmjs.com/package/@cantoo/pdf-lib' }],
  },
  {
    title: 'PDF to Text',
    path: '/pdf-to-text',
    description: 'Extract the text of a PDF, page by page, with OCR for scanned pages',
    icon: FileType,
    categories: [CATEGORIES.PDF],
    searchTags: ['pdf', 'text', 'extract', 'txt', 'copy', 'convert', 'ocr', 'scan', 'tesseract'],
    component: lazy(() => import('@/tools/PdfToText')),
    online: false,
    dependencies: [
      { name: 'pdf.js', url: 'https://mozilla.github.io/pdf.js/' },
      { name: 'tesseract.js', url: 'https://github.com/naptha/tesseract.js' },
    ],
  },
  {
    title: 'Protect / Unlock PDF',
    path: '/pdf-password',
    description: 'Add a password to a PDF (AES-256) or remove its password and restrictions',
    icon: FileLock,
    categories: [CATEGORIES.PDF, CATEGORIES.SECURITY],
    searchTags: ['pdf', 'password', 'protect', 'encrypt', 'unlock', 'decrypt', 'remove', 'restrictions', 'aes'],
    component: lazy(() => import('@/tools/PdfPassword')),
    online: false,
    dependencies: [{ name: 'qpdf', url: 'https://qpdf.sourceforge.io' }],
  },
]

/** Tools shown in this deployment (online tools are hidden when DISABLE_ONLINE_TOOLS is set) */
export const availableTools = runtimeConfig.DISABLE_ONLINE_TOOLS ? tools.filter((t) => !t.online) : tools
